-- Active: 1769622808934@@127.0.0.1@3306@pulse
-- 1. CREAZIONE DATABASE
CREATE DATABASE IF NOT EXISTS Pulse;
USE Pulse;

-- 2. UTENTI E SOCIAL CORE
CREATE TABLE IF NOT EXISTS Utente (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Bio VARCHAR(255),
    Avatar_URL VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Segui (
    IDSeguitore INT NOT NULL,
    IDSeguito INT NOT NULL,
    Data_Seguimento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (IDSeguitore, IDSeguito),
    CONSTRAINT FK_Seg_Seguitore FOREIGN KEY (IDSeguitore) REFERENCES Utente(ID) ON DELETE CASCADE,
    CONSTRAINT FK_Seg_Seguito FOREIGN KEY (IDSeguito) REFERENCES Utente(ID) ON DELETE CASCADE
);

-- 3. FILM E PERSONE (Dati compatibili con API TMDB)
CREATE TABLE IF NOT EXISTS Film (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TMDB_ID INT UNIQUE NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Original_Title VARCHAR(255),
    Original_Language CHAR(2),
    Overview TEXT,
    Release_Date DATE,
    Runtime SMALLINT,
    Poster_Path VARCHAR(255),
    Backdrop_Path VARCHAR(255),
    Popularity DECIMAL(10,4),
    Vote_Average DECIMAL(3,1),
    Vote_Count INT,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY IDX_Film_Title (Title)
);

CREATE TABLE IF NOT EXISTS Persona (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TMDB_ID INT UNIQUE NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Biography TEXT,
    Profile_Path VARCHAR(255),
    KEY IDX_Persona_Name (Name)
);

CREATE TABLE IF NOT EXISTS Partecipazione (
    IDPersona INT NOT NULL,
    IDFilm INT NOT NULL,
    Job VARCHAR(100) NOT NULL, -- Actor, Director, etc.
    Character_Name VARCHAR(255),
    PRIMARY KEY (IDPersona, IDFilm, Job),
    CONSTRAINT FK_Part_Persona FOREIGN KEY (IDPersona) REFERENCES Persona(ID) ON DELETE CASCADE,
    CONSTRAINT FK_Part_Film FOREIGN KEY (IDFilm) REFERENCES Film(ID) ON DELETE CASCADE
);

-- 4. GENERI E COMMUNITY
CREATE TABLE IF NOT EXISTS Genere (
    ID INT PRIMARY KEY, -- Usare ID di TMDB
    Name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Caratterizzazione (
    IDFilm INT NOT NULL,
    IDGenere INT NOT NULL,
    PRIMARY KEY (IDFilm, IDGenere),
    CONSTRAINT FK_Car_Film FOREIGN KEY (IDFilm) REFERENCES Film(ID) ON DELETE CASCADE,
    CONSTRAINT FK_Car_Genere FOREIGN KEY (IDGenere) REFERENCES Genere(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Community (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDGenere INT UNIQUE NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Descrizione TEXT,
    CONSTRAINT FK_Comm_Genere FOREIGN KEY (IDGenere) REFERENCES Genere(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Iscrizione_Community (
    IDUtente INT NOT NULL,
    IDCommunity INT NOT NULL,
    PRIMARY KEY (IDUtente, IDCommunity),
    CONSTRAINT FK_Isc_Utente FOREIGN KEY (IDUtente) REFERENCES Utente(ID) ON DELETE CASCADE,
    CONSTRAINT FK_Isc_Comm FOREIGN KEY (IDCommunity) REFERENCES Community(ID) ON DELETE CASCADE
);

-- 5. ATTIVITÀ UTENTE: LOG, POST, VISIONE
CREATE TABLE IF NOT EXISTS Log (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDUtente INT NOT NULL,
    IDFilm INT NOT NULL,
    Data DATE NOT NULL,
    Voto DECIMAL(2,1),
    Recensione TEXT,
    Data_Pubblicazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Log_Utente FOREIGN KEY (IDUtente) REFERENCES Utente(ID) ON DELETE CASCADE,
    CONSTRAINT FK_Log_Film FOREIGN KEY (IDFilm) REFERENCES Film(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Post (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDUtente INT NOT NULL,
    IDCommunity INT DEFAULT NULL,
    Contenuto TEXT NOT NULL,
    Data_Pubblicazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Post_Utente FOREIGN KEY (IDUtente) REFERENCES Utente(ID) ON DELETE CASCADE,
    CONSTRAINT FK_Post_Comm FOREIGN KEY (IDCommunity) REFERENCES Community(ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Visione (
    IDUtente INT NOT NULL,
    IDFilm INT NOT NULL,
    Is_Watched BOOLEAN DEFAULT NULL,
    In_Watchlist BOOLEAN DEFAULT NULL,
    Liked BOOLEAN DEFAULT NULL,
    Rating DECIMAL(2,1) DEFAULT NULL,
    Is_Favourite BOOLEAN DEFAULT NULL,
    PRIMARY KEY (IDUtente, IDFilm),
    CONSTRAINT FK_Vis_Utente FOREIGN KEY (IDUtente) REFERENCES Utente(ID) ON DELETE CASCADE,
    CONSTRAINT FK_Vis_Film FOREIGN KEY (IDFilm) REFERENCES Film(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_Rating CHECK (Rating IS NULL OR (Rating >= 0.5 AND Rating <= 5.0))
);

-- 6. LISTE E TAG
CREATE TABLE IF NOT EXISTS Lista (
    IDLista INT PRIMARY KEY AUTO_INCREMENT,
    Titolo VARCHAR(255) NOT NULL,
    Descrizione VARCHAR(255),
    IDUtente INT NOT NULL,
    CONSTRAINT FK_Lista_Creatore FOREIGN KEY (IDUtente) REFERENCES Utente(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Lista_Film (
    IDLista INT NOT NULL,
    IDFilm INT NOT NULL,
    PRIMARY KEY (IDLista, IDFilm),
    CONSTRAINT FK_LF_Lista FOREIGN KEY (IDLista) REFERENCES Lista(IDLista) ON DELETE CASCADE,
    CONSTRAINT FK_LF_Film FOREIGN KEY (IDFilm) REFERENCES Film(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Tag (
    IDTag INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Lista_Tag (
    IDLista INT NOT NULL,
    IDTag INT NOT NULL,
    PRIMARY KEY (IDLista, IDTag),
    CONSTRAINT FK_LT_Lista FOREIGN KEY (IDLista) REFERENCES Lista(IDLista) ON DELETE CASCADE,
    CONSTRAINT FK_LT_Tag FOREIGN KEY (IDTag) REFERENCES Tag(IDTag) ON DELETE CASCADE
);

-- 7. COMMENTI E MI PIACE
CREATE TABLE IF NOT EXISTS Commento (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDUtente INT NOT NULL,
    Contenuto TEXT NOT NULL,
    IDLog INT DEFAULT NULL,
    IDPost INT DEFAULT NULL,
    IDCommentoPadre INT DEFAULT NULL,
    Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_C_Utente FOREIGN KEY (IDUtente) REFERENCES Utente(ID) ON DELETE CASCADE,
    CONSTRAINT FK_C_Log FOREIGN KEY (IDLog) REFERENCES Log(ID) ON DELETE CASCADE,
    CONSTRAINT FK_C_Post FOREIGN KEY (IDPost) REFERENCES Post(ID) ON DELETE CASCADE,
    CONSTRAINT FK_C_Parent FOREIGN KEY (IDCommentoPadre) REFERENCES Commento(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MiPiace (
    IDUtente INT NOT NULL,
    IDLog INT DEFAULT NULL,
    IDPost INT DEFAULT NULL,
    IDCommento INT DEFAULT NULL,
    PRIMARY KEY (IDUtente, IDLog, IDPost, IDCommento), -- Nota: Questo richiede logica PHP per gestire i NULL
    CONSTRAINT FK_L_Utente FOREIGN KEY (IDUtente) REFERENCES Utente(ID) ON DELETE CASCADE,
    CONSTRAINT FK_L_Log FOREIGN KEY (IDLog) REFERENCES Log(ID) ON DELETE CASCADE,
    CONSTRAINT FK_L_Post FOREIGN KEY (IDPost) REFERENCES Post(ID) ON DELETE CASCADE,
    CONSTRAINT FK_L_Comm FOREIGN KEY (IDCommento) REFERENCES Commento(ID) ON DELETE CASCADE
);
